version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: octoblu/pnpm:latest

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pnpm i --frozen-lockfile
      - run:
          name: Lint
          command: pnpm run lint
      - run:
          name: Build
          command: pnpm run build
      - run:
          name: Test
          command: pnpm run test


  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pnpm i --frozen-lockfile
      - run:
          name: Lint
          command: pnpm run lint
      - run:
          name: Build
          command: pnpm run build
      - run:
          name: Test
          command: pnpm run test
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish
          command: pnpm publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - deploy:
          filters:
            branches:
              only: master
